// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycxiiacxtnkdifeuvrew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljeGlpYWN4dG5rZGlmZXV2cmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjA1MzksImV4cCI6MjA2NjUzNjUzOX0.H-iAIR6V8ZgGmjEf33GXvEbCsKXVi6xCjjMCytKnH_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);